services:
  app:
    build: .
    container_name: backend-app
    ports:
      - "8080:8080"
      - "8000:8000"
    environment:
      TZ: Asia/Bangkok
    volumes:
      - ./secret.yml:/app/config/secret.yml:ro