import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: const [
          Android(),
        ]),
      ),
    );
  }
}

class Android extends StatelessWidget {
  const Android({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 430,
          height: 464,
          clipBehavior: Clip.antiAlias,
          decoration: const BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              const Positioned(
                left: 162,
                top: 13,
                child: SizedBox(
                  width: 178,
                  height: 39,
                  child: Text(
                    'Phiếu điểm',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 20,
                      fontFamily: 'Be Vietnam Pro',
                      fontWeight: FontWeight.w400,
                      height: 1.50,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 21,
                top: 49,
                child: Container(
                  width: 387,
                  height: 346,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: Colors.black.withOpacity(0.50),
                      ),
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 34,
                top: 74.60,
                child: SizedBox(
                  width: 38,
                  height: 15.36,
                  child: Text(
                    'Ngành:',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      height: 1.24,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 262,
                top: 73.57,
                child: SizedBox(
                  width: 102,
                  height: 15.36,
                  child: Text(
                    'Kĩ thuật phần miền',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF393938),
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w700,
                      height: 1.24,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 276,
                top: 116.28,
                child: SizedBox(
                  width: 110,
                  height: 14.33,
                  child: Text(
                    '2251172362',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF393938),
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w700,
                      height: 1.24,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 34,
                top: 115.55,
                child: SizedBox(
                  width: 90,
                  height: 14.33,
                  child: Text(
                    'Mã sinh viên:',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      height: 1.24,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 34,
                top: 94.05,
                child: SizedBox(
                  width: 44,
                  height: 14.33,
                  child: Text(
                    'Họ tên:',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      height: 1.24,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 250,
                top: 94,
                child: SizedBox(
                  width: 153,
                  height: 14.33,
                  child: Text(
                    'Hà Văn Thắng',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF393938),
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w700,
                      height: 1.24,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 34,
                top: 142.17,
                child: SizedBox(
                  width: 388,
                  height: 24.57,
                  child: Text(
                    'Đề tài:  Xây dựng ứng dụng quản lý đồ án tốt nghiệp.',
                    style: TextStyle(
                      color: Color(0xFF111827),
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      height: 2,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 34,
                top: 173.90,
                child: SizedBox(
                  width: 90,
                  height: 14.33,
                  child: Text(
                    'GVHD:',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      height: 1.24,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 33,
                top: 139,
                child: Container(
                  width: 360,
                  decoration: const ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 0.50,
                        color: Color(0xFF8C8484),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 316,
                top: 211,
                child: Opacity(
                  opacity: 0.80,
                  child: Container(
                    width: 48,
                    height: 22,
                    decoration: ShapeDecoration(
                      color: Colors.white,
                      shape: RoundedRectangleBorder(
                        side: BorderSide(
                          width: 1,
                          color: Colors.black.withOpacity(0.50),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 316,
                top: 248,
                child: Opacity(
                  opacity: 0.80,
                  child: Container(
                    width: 48,
                    height: 22,
                    decoration: ShapeDecoration(
                      color: Colors.white,
                      shape: RoundedRectangleBorder(
                        side: BorderSide(
                          width: 1,
                          color: Colors.black.withOpacity(0.50),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 316,
                top: 286,
                child: Opacity(
                  opacity: 0.80,
                  child: Container(
                    width: 48,
                    height: 22,
                    decoration: ShapeDecoration(
                      color: Colors.white,
                      shape: RoundedRectangleBorder(
                        side: BorderSide(
                          width: 1,
                          color: Colors.black.withOpacity(0.50),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 316,
                top: 327,
                child: Opacity(
                  opacity: 0.80,
                  child: Container(
                    width: 48,
                    height: 22,
                    decoration: ShapeDecoration(
                      color: Colors.white,
                      shape: RoundedRectangleBorder(
                        side: BorderSide(
                          width: 1,
                          color: Colors.black.withOpacity(0.50),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 39,
                top: 215,
                child: SizedBox(
                  width: 266,
                  height: 14,
                  child: Text(
                    'Hình thức trình bày báo cáo',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      height: 1.24,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 39,
                top: 247,
                child: SizedBox(
                  width: 266,
                  height: 14,
                  child: Text(
                    'Nội dung lý thuyết và cơ sở khoa học',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      height: 1.24,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 39,
                top: 290,
                child: SizedBox(
                  width: 266,
                  height: 14,
                  child: Text(
                    'Mức độ nghiên cứu và phân tích',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      height: 1.24,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 39,
                top: 331,
                child: SizedBox(
                  width: 266,
                  height: 14,
                  child: Text(
                    'Khả năng trình bày',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      height: 1.24,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 39,
                top: 370,
                child: SizedBox(
                  width: 266,
                  height: 14,
                  child: Text(
                    'Tổng điểm: ',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      height: 1.24,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 106,
                top: 367,
                child: Opacity(
                  opacity: 0.80,
                  child: Container(
                    width: 48,
                    height: 22,
                    decoration: ShapeDecoration(
                      color: Colors.black.withOpacity(0.25),
                      shape: RoundedRectangleBorder(
                        side: BorderSide(
                          width: 1,
                          color: Colors.black.withOpacity(0.50),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 34,
                top: 56,
                child: SizedBox(
                  width: 38,
                  height: 15.36,
                  child: Text(
                    'Khoa:',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      height: 1.24,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 251,
                top: 55,
                child: SizedBox(
                  width: 117,
                  height: 15,
                  child: Text(
                    'Công nghê thông tin',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Color(0xFF393938),
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w700,
                      height: 1.24,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 150,
                top: 408,
                child: Container(
                  width: 117,
                  height: 30,
                  color: const Color(0xFF2F7CD3),
                ),
              ),
              const Positioned(
                left: 150,
                top: 414,
                child: SizedBox(
                  width: 117,
                  height: 24,
                  child: Text(
                    'Xác nhận',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
